import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"

import { fmt, fmtCompact, rowMetrics, sheetTotals } from "@/lib/rows"
import { slugify, timestamp, type Sheet } from "@/lib/sheet"

/** Render the sheet as a one-table A4 PDF and trigger the download. */
export function exportSheetPdf({ rows, meta }: Sheet): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })
  const pageW = doc.internal.pageSize.getWidth()
  const showAmount = meta.rate > 0

  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.text("GLASS DRAWING - EXTRACTED SIZES", pageW / 2, 16, { align: "center" })

  const info: string[] = []
  if (meta.party) info.push(`Party: ${meta.party}`)
  if (meta.spec) info.push(`Spec: ${meta.spec}`)
  if (showAmount) info.push(`Rate: ${fmtCompact(meta.rate)} /sq.ft`)
  info.push(`Date: ${new Date().toLocaleDateString("en-IN")}`)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(90)
  doc.text(info.join("   |   "), pageW / 2, 22, { align: "center" })

  let top = 28
  if (meta.notes.trim()) {
    const lines = doc.splitTextToSize(`Notes: ${meta.notes.trim()}`, pageW - 28)
    doc.text(lines, pageW / 2, top, { align: "center" })
    top += lines.length * 4 + 2
  }
  doc.setTextColor(0)

  const head = [
    "#",
    "Label",
    `W (${meta.unit})`,
    `H (${meta.unit})`,
    "Qty",
    "Holes",
    "C/O",
    'Ch. W"',
    'Ch. H"',
    "Area",
  ]
  if (showAmount) head.push("Amount")

  const body = rows.map((row, i) => {
    const m = rowMetrics(row, meta.unit, meta.rate)
    const cells = [
      String(i + 1),
      row.label,
      row.width,
      row.height,
      String(row.qty),
      String(row.holes),
      String(row.cutouts),
      m.chargeW ? String(m.chargeW) : "",
      m.chargeH ? String(m.chargeH) : "",
      fmt(m.area),
    ]
    if (showAmount) cells.push(fmt(m.amount))
    return cells
  })

  const totals = sheetTotals(rows, meta.unit, meta.rate, meta.weightPerSqft)
  const footCells = [
    "",
    "TOTAL",
    "",
    "",
    String(totals.pieces),
    String(totals.holes),
    String(totals.cutouts),
    "",
    "",
    fmt(totals.area),
  ]
  if (showAmount) footCells.push(fmt(totals.amount))

  autoTable(doc, {
    head: [head],
    body,
    foot: [footCells],
    startY: top,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 1.8, halign: "center", lineColor: 160 },
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: "bold" },
    footStyles: { fillColor: [229, 231, 235], textColor: 0, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [246, 247, 249] },
    columnStyles: { 0: { cellWidth: 8 }, 1: { halign: "left" } },
    margin: { left: 12, right: 12 },
  })

  const endY =
    (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? top

  if (meta.weightPerSqft > 0) {
    doc.setFont("helvetica", "bold")
    doc.setFontSize(9)
    doc.text(
      `Estimated weight: ${fmt(totals.weight)} kg  (${fmtCompact(meta.weightPerSqft)} kg/sq.ft)`,
      pageW - 12,
      endY + 6,
      { align: "right" },
    )
  }

  const pages = doc.getNumberOfPages()
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(7)
    doc.setTextColor(140)
    doc.text(
      `Generated by Glass Drawing AI - sizes are AI-extracted, verify before cutting.`,
      12,
      doc.internal.pageSize.getHeight() - 8,
    )
    doc.text(
      `Page ${p} / ${pages}`,
      pageW - 12,
      doc.internal.pageSize.getHeight() - 8,
      { align: "right" },
    )
  }

  doc.save(`${slugify(meta.party, "drawing")}_sizes_${timestamp()}.pdf`)
}
